name: Cypress Edge-Browser Testing - DailyRun

on:
  schedule:
     # UTC time is setup here i.e. 2:30 AM (daily) which is equal to 8:00 AM IST
    - cron: '30 2 * * *'

jobs:
  cypress-crossbrowser-testing:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        timeout-minutes: 60
        with:
          # Run on Edge browser
          browser: edge
          record: true
          #group: GH Action cross-browser
          #start: npm start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARDKEY }}
