name: Cypress Chrome-Browser Testing - Trigger from Dev

on: workflow_call

jobs:
  cypress-crossbrowser-testing:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run tests
        uses: cypress-io/github-action@v4
        timeout-minutes: 60
        with:
          # Run on all different browsers mentioned in matrix above
          browser: chrome
          record: true
          #group: GH Action cross-browser
          #start: npm start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_DASHBOARDKEY }}
      - name: 'trigger cypress'
        run: |
         curl -X POST https://api.github.com/repos/raintreeinc/kiosk_frontend/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "Trigger", "client_payload": { "ACCESSKEY": "${{ secrets.AWS_ACCESS_KEY_ID }}", "SECRETKEY": "${{ secrets.AWS_SECRET_ACCESS_KEY }}"  }}'
